# Generated by Django 3.2.13 on 2022-06-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.TextField(blank=True, default='', null=True)),
                ('order_email', models.TextField(blank=True, default='', null=True)),
                ('order_address', models.TextField(blank=True, default='', null=True)),
                ('order_item', models.TextField(blank=True, default='', null=True)),
                ('is_valid', models.BooleanField(default=False)),
            ],
        ),
    ]
