# Generated by Django 3.2.13 on 2022-06-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_info',
            name='order_price',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
