# Generated by Django 3.2.9 on 2022-03-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reserve_inform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_userId', models.TextField(default='')),
                ('reserve_name', models.TextField(default='')),
                ('reserve_email', models.TextField(default='')),
                ('reserve_status', models.TextField(default='初始狀態')),
                ('reserve_time', models.TextField()),
                ('reserve_num', models.CharField(max_length=2)),
            ],
        ),
    ]
