# Generated by Django 3.2.9 on 2022-04-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0003_rename_reserve_search_status_reserve_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve_inform',
            name='reserve_num',
        ),
        migrations.AddField(
            model_name='reserve_inform',
            name='reserve_email_confirm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reserve_inform',
            name='reserve_name_confirm',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reserve_inform',
            name='reserve_time_confirm',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reserve_search',
            name='reserve_search_status',
            field=models.TextField(default='搜尋初始狀態'),
        ),
    ]
