# Generated by Django 3.2.9 on 2022-04-03 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_auto_20220403_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve_inform',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='儲存日期'),
        ),
    ]
