# Generated by Django 3.2.9 on 2022-04-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_rename_add_date_reserve_inform_reserve_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve_inform',
            old_name='reserve_time',
            new_name='reserve_datetime_confirm',
        ),
        migrations.RemoveField(
            model_name='reserve_inform',
            name='reserve_time_confirm',
        ),
    ]
