# Generated by Django 3.2.9 on 2022-04-03 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0007_auto_20220403_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime_confirm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='儲存日期'),
        ),
    ]
