# Generated by Django 3.2.9 on 2022-04-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0008_alter_reserve_inform_reserve_datetime_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime_confirm',
            field=models.TextField(default=''),
        ),
    ]
