# Generated by Django 3.2.9 on 2022-04-03 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0009_alter_reserve_inform_reserve_datetime_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='預訂日期'),
        ),
    ]
