# Generated by Django 3.2.9 on 2022-04-09 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0011_alter_reserve_inform_reserve_datetime_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_email',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_email_confirm',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_name_confirm',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_userId',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
