# Generated by Django 3.2.9 on 2022-04-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0012_auto_20220409_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserve_cancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserve_cancel_userId', models.TextField(default='')),
                ('reserve_cancel_name', models.TextField(default='')),
                ('reserve_cancel_email', models.TextField(default='')),
                ('reserve_cancel_status', models.TextField(default='取消初始狀態')),
            ],
        ),
    ]
