# Generated by Django 3.2.9 on 2022-04-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0014_auto_20220409_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime',
            field=models.DateTimeField(verbose_name='預訂日期'),
        ),
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime_confirm',
            field=models.DateTimeField(verbose_name='預訂日期'),
        ),
    ]
