# Generated by Django 3.2.9 on 2022-04-09 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0015_auto_20220409_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='預訂日期'),
        ),
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime_confirm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='預訂日期'),
        ),
    ]
