# Generated by Django 3.2.9 on 2022-04-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0016_auto_20220409_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='userId_mapping_blockId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.TextField(default='')),
                ('blockId', models.TextField(default='')),
            ],
        ),
    ]
