# Generated by Django 3.2.13 on 2022-05-10 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0017_userid_mapping_blockid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve_inform',
            name='reserve_datetime_confirm',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='預訂日期確認'),
        ),
    ]
